# Data Preparation

In [2]:
import pandas as pd

In [3]:
df23 = pd.read_csv('2023_with_myco.csv')
df23

,NOLA_ID,Location,State.abbreviation,Plot/BagID,Block_No,Replicate,Treatement_ID,Residue_level,Tillage,Fungicide,...,Lab.code,Notes on treatements,Selected for MYCOTOXIN TESTING,Planting.Date,Date.grain.collected,GPS,Unnamed: 17,Unnamed: 18,Aflatoxin,Fumonisin
0,1,Columbia,MO,101,1.0,1,1,HR,NoTill,NS,...,Mandy Bish,NaN,YES,4/14/23,10/5/23,"38.8910972, -92.2112472222222",NaN,NaN,0.0,NaN
1,2,Columbia,MO,202,2.0,2,1,HR,NoTill,NS,...,Mandy Bish,NaN,YES,4/14/23,10/5/23,"38.8910972, -92.2112472222222",NaN,NaN,0.0,NaN
2,3,Columbia,MO,302,2.0,3,1,HR,NoTill,NS,...,Mandy Bish,NaN,YES,4/14/23,10/5/23,"38.8910972, -92.2112472222222",NaN,NaN,0.0,9.5
3,4,Columbia,MO,401,1.0,4,1,HR,NoTill,NS,...,Mandy Bish,NaN,YES,4/14/23,10/5/23,"38.8910972, -92.2112472222222",NaN,NaN,0.0,3.9
4,5,Columbia,MO,502,2.0,5,1,HR,NoTill,NS,...,Mandy Bish,NaN,YES,4/14/23,10/5/23,"38.8910972, -92.2112472222222",NaN,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,395,Lancaster,WI,203,NaN,2,3,NaN,Tilled,NS,...,Daimon,65,YES,5/18/23,11/7/23,"42.829174, -90.789145",NaN,NaN,NaN,NaN
175,398,Lancaster,WI,302,NaN,3,3,NaN,Tilled,NS,...,Daimon,65,YES,5/18/23,11/7/23,"42.829174, -90.789145",NaN,NaN,NaN,NaN
176,400,Lancaster,WI,304,NaN,3,1,NaN,Tilled,NS,...,Daimon,65,YES,5/18/23,11/7/23,"42.829174, -90.789145",NaN,NaN,NaN,NaN
177,401,Lancaster,WI,401,NaN,4,1,NaN,Tilled,NS,...,Daimon,65,YES,5/18/23,11/7/23,"42.829174, -90.789145",NaN,NaN,NaN,NaN
178,403,Lancaster,WI,403,NaN,4,3,NaN,Tilled,NS,...,Daimon,65,YES,5/18/23,11/7/23,"42.829174, -90.789145",NaN,NaN,NaN,NaN

In [4]:
df24 = pd.read_csv('2024_with_myco.csv')
df24

,NOLA_ID,Location,State.abbreviation,Unnamed: 3,Unnamed: 4,Replicate_No,Treatement_ID,Residue_level,Tillage,Fungicide,Hybrid,Lab.code,Planting.Date,Harvest.date,GPS,Aflatoxin,Fumonisin
0,1,KY-2,KY-2,01HRF_101,101.0,1,01HRF,High,NoTill,NONE,DKC63-91,Wise,5/13/24,9/11/24,"37.09892, -87.87548",0.0,2.40
1,2,KY-2,KY-2,01HRF_104,104.0,1,01HRF,High,NoTill,NONE,DKC111-35,Wise,5/13/24,9/11/24,"37.09892, -87.87549",0.0,0.12
2,3,KY-2,KY-2,01HRF_202,202.0,2,01HRF,High,NoTill,NONE,DKC111-35,Wise,5/13/24,9/11/24,"37.09892, -87.87550",0.0,0.91
3,4,KY-2,KY-2,01HRF_203,203.0,2,01HRF,High,NoTill,NONE,DKC63-91,Wise,5/13/24,9/11/24,"37.09892, -87.87551",0.0,0.03
4,5,KY-2,KY-2,01HRF_301,301.0,3,01HRF,High,NoTill,NONE,DKC63-91,Wise,5/13/24,9/11/24,"37.09892, -87.87552",0.0,1.20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
159,164,SERF,Iowa,103,NaN,1,2,Till,Till,NONE,P1185Q,Robertson,5/20/24,9/24/24,"41.20329, -91.48677",0.0,0.00
160,165,SERF,Iowa,303,NaN,2,2,Till,Till,NONE,P1185Q,Robertson,5/20/24,9/24/24,"41.20329, -91.48678",0.0,0.01
161,166,SERF,Iowa,503,NaN,3,2,Till,Till,NONE,P1185Q,Robertson,5/20/24,9/24/24,"41.20329, -91.48679",0.0,0.01
162,167,SERF,Iowa,604,NaN,4,2,Till,Till,NONE,P1185Q,Robertson,5/20/24,9/24/24,"41.20329, -91.48680",0.0,0.01
163,168,SERF,Iowa,304,NaN,5,2,Till,Till,NONE,P1185Q,Robertson,5/20/24,9/24/24,"41.20329, -91.48681",0.0,0.02

In [5]:
df23.columns

Index(['NOLA_ID', 'Location', 'State.abbreviation', 'Plot/BagID', 'Block_No',
       'Replicate', 'Treatement_ID', 'Residue_level', 'Tillage', 'Fungicide',
       'Hybrid', 'Lab.code', 'Notes on treatements',
       'Selected for MYCOTOXIN TESTING', 'Planting.Date',
       'Date.grain.collected', 'GPS', 'Unnamed: 17', 'Unnamed: 18',
       'Aflatoxin', 'Fumonisin'],
      dtype='object')

In [ ]:
df24

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,Column11,Column12,Column13,Column14,Column15
0,NOLA_ID,Location,State.abbreviation,NaN,NaN,Replicate_No,Treatement_ID,Residue_level,Tillage,Fungicide,Hybrid,Lab.code,Planting.Date,Harvest.date,GPS
1,1,KY,KY-2,01HRF_101,101.0,1,01HRF,High,NoTill,NONE,DKC63-91,Wise,5/13/24,9/11/24,"37.09892, -87.87548"
2,2,KY,KY-2,01HRF_104,104.0,1,01HRF,High,NoTill,NONE,DKC111-35,Wise,5/13/24,9/11/24,"37.09892, -87.87549"
3,3,KY,KY-2,01HRF_202,202.0,2,01HRF,High,NoTill,NONE,DKC111-35,Wise,5/13/24,9/11/24,"37.09892, -87.87550"
4,4,KY,KY-2,01HRF_203,203.0,2,01HRF,High,NoTill,NONE,DKC63-91,Wise,5/13/24,9/11/24,"37.09892, -87.87551"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
993,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
set(df23.columns) == set(df24.columns)

False

In [14]:
set(df23.columns) - set(df24.columns)
set(df24.columns) - set(df23.columns)

set()

In [13]:
df24 = df24.drop(columns=["Unnamed: 3", "Unnamed: 4"], errors="ignore")

In [9]:
df23["source"] = "dataset_23"
df24["source"] = "dataset_24"

In [10]:
rename_map = {
    "Date.grain.collected": "Harvest.date",
    "Replicate": "Replicate_No",
    "Selected.for.MYCOTOXIN.TESTING": "Selected.for.mycotoxin.testing"
}

df23 = df23.rename(columns=rename_map)
df23.columns

Index(['NOLA_ID', 'Location', 'State.abbreviation', 'Plot/BagID', 'Block_No',
       'Replicate_No', 'Treatement_ID', 'Residue_level', 'Tillage',
       'Fungicide', 'Hybrid', 'Lab.code', 'Notes on treatements',
       'Selected for MYCOTOXIN TESTING', 'Planting.Date', 'Harvest.date',
       'GPS', 'Unnamed: 17', 'Unnamed: 18', 'Aflatoxin', 'Fumonisin',
       'source'],
      dtype='object')

In [11]:
df23.columns.equals(df24.columns)

False

In [ ]:
missing = df23.columns.difference(df24.columns)
print("Missing in df24:", list(missing))

# add them as empty columns
for c in missing:
    df24[c] = pd.NA

# now reorder df24 to match df23
df24 = df24[df23.columns]

# confirm
print(df23.columns.equals(df24.columns))

Missing in df24: ['Block_No', 'Notes on treatements', 'Plot/BagID', 'Selected for MYCOTOXIN TESTING']
True

In [ ]:
set(df23.columns) == set(df24.columns)

False

Add year label before stacking

In [ ]:
df23["source"] = "dataset_23"
df24["source"] = "dataset_24"

Order columns

In [ ]:
df24 = df24[df23.columns]

Combine and Sanity Checks

In [15]:
# Stack (row-bind)
combined_df = pd.concat([df23, df24], ignore_index=True)

print("df1 shape:", df23.shape)
print("df2 shape:", df24.shape)
print("combined shape:", combined_df.shape)

df1 shape: (179, 22)
df2 shape: (164, 16)
combined shape: (343, 22)

In [16]:
master_df = combined_df
master_df.to_csv("master_df.csv", index=False)

In [17]:
df_all = pd.concat([df23, df24], ignore_index=True)

In [ ]:
df_all.to_csv("2024_2025_combined.csv", index=False)

In [ ]:
df_all.shape

(331, 18)